Feat: Dynamic Enums (Advanced)
EOX-A/git-clerk pull request #67
Opened 2024-12-24 13:59 UTC by srijitcoder

- fix: logic for paste in create file input improved
- chores: refactored the paste code a bit
- fix: open existing file with add button
- feat: mobile view for action
- feat: added upload image and video to editor
- chores: path added to upload
- fix: fiel url through commit sha
- feat: added major css changes for mobile
- chores: remove console
- chores: nav bar mobile ui
- fix: display none property on label
- feat: automation UI based on automation steps
- feat: added major functionality for automation
- fix: styling eox-jsonform and dialog box
- fix: reduced reduntant code
- feat: added nav button with automation
- fix: ui update add button
- fix: undefined jsonforminstance
- fix: added path for both /storytelling and /narattives for schemaMap
- feat: add type navigation
- fix: make repo owner part of githubRepo config and make authToken fetch as promise from async
- fix: remove async
- fix: snackbar warning
- feat: added duplicate feature
- fix: error passing wrong prop
- fix: justify center of suggestionlist
- feat: added upload multiple files
- fix: compare oldContent with newContent
- feat: added dynamic enum generation
- fix: styling for min-height
- chore: update readme
- chore: add release-please action
- chore: update manifest and config
- chore: update manifest
- chore: rename file
- chore(main): release git-clerk 1.0.0 (#60)
- chore: update release-please config
- fix: make enum path part of config.js
- feat: add dependency (#61)
- fix: remove symbols from branch slug name
- fix: removed  props to
- Fix: remove symbols from branch's slug name (#64)
- chore(main): release git-clerk 1.1.0 (#62)
- feat: added basic custom editor interface code
- feat: experiment with abstract editor
- feat: input generation using Abstract Editor

2025-01-22 13:28 UTC, silvester-pari commented on index.html
> +    <script src="https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.js"></script>
Could we move this import to the `config.js`? This way all the custom functionality would be self-contained there

2025-01-28 10:34 UTC, silvester-pari commented on public/config.js
> +  "osc:type": "product",
It would be great if this would also work for themes, eo missions, etc.

2025-02-06 16:14 UTC, silvester-pari requested changes

2025-02-10 09:44 UTC, srijitcoder commented on src/views/FileEditView.vue
> +          `${path}/catalog.json`,
Done ✅

2025-02-10 09:44 UTC, srijitcoder commented on public/config.js
> +        ? newIds.map(customEditorInterface.customDataDecoder)
Done ✅

2025-02-10 09:45 UTC, srijitcoder commented on public/config.js
> +      await createAndUpdateFile(
Done ✅

2025-02-10 15:39 UTC, merged